"""added new columns for subtasks and completed status

Revision ID: 25cff2077e84
Revises: 8f2a9d1c4b7e
Create Date: 2026-03-03 08:33:32.231003

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '25cff2077e84'
down_revision: Union[str, Sequence[str], None] = '8f2a9d1c4b7e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
