"""empty message

Revision ID: 61d0cd2f3906
Revises: 
Create Date: 2026-02-27 04:40:05.804562

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '61d0cd2f3906'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('todos', sa.Column('description', sa.String(), nullable=True))
    op.add_column('todos', sa.Column('deadline', sa.DateTime(), nullable=True))
    op.add_column('todos', sa.Column('created_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('todos', 'created_at')
    op.drop_column('todos', 'deadline')
    op.drop_column('todos', 'description')
    # ### end Alembic commands ###
